# Generated by Django 4.1.2 on 2022-10-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provedor', '0002_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='provedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='provedor.provedor'),
        ),
    ]
